export const CONSTANTS = {
    DEFAULT_HOSTNAME: "localhost",
    DEFAULT_PORT: 8080,
    HOSTNAME_SETTINGS_KEY: "recentHostname",
    PORT_SETTINGS_KEY: "recentPort",
    RECENT_UI_STATE_VALUES_KEY: "recentStateValues",
    RECENT_UI_STATE_DECL_KEY: "recentStateDecls",
    THROTTLE_SET_STATE: 500,
    THROTTLE_PROTOBUF_MSG_PARSE: 16,
    THROTTLE_FIELD_UPDATE: 16
};